import tkinter as tk

window = tk.Tk()

window.title("Address Entry Form")
window.columnconfigure([0,1], weight=1, minsize=50)
window.rowconfigure([0,1,2,3,4,5,6,7], weight=1, minsize=30)
label1 = tk.Label(window, text="First Name:")
label2 = tk.Label(window, text="Last Name:")
label3 = tk.Label(window, text="Address Line 1:")
label4 = tk.Label(window, text="Address Line 2:")
label5 = tk.Label(window, text="City:")
label6 = tk.Label(window, text="State/Province:")
label7 = tk.Label(window, text="Postal Code:")
label8 = tk.Label(window, text="Country:")
entry1 = tk.Entry(window, width=50)
entry2 = tk.Entry(window, width=50)
entry3 = tk.Entry(window, width=50)
entry4 = tk.Entry(window, width=50)
entry5 = tk.Entry(window, width=50)
entry6 = tk.Entry(window, width=50)
entry7 = tk.Entry(window, width=50)
entry8 = tk.Entry(window, width=50)
def clean_content():
    entry1.delete(0, tk.END)
    entry2.delete(0, tk.END)
    entry3.delete(0, tk.END)
    entry4.delete(0, tk.END)
    entry5.delete(0, tk.END)
    entry6.delete(0, tk.END)
    entry7.delete(0, tk.END)
    entry8.delete(0, tk.END)

def submit_text():
    entry1.get()
    entry2.get()
    entry3.get()
    entry4.get()
    entry5.get()
    entry6.get()
    entry7.get()
    entry8.get()

button1 = tk.Button(window, text="Submit", command=submit_text)
button2 = tk.Button(window, text="Clear", command=clean_content)

label1.grid(row=0, column=0, sticky=tk.E)
label2.grid(row=1, column=0, sticky=tk.E)
label3.grid(row=2, column=0, sticky=tk.E)
label4.grid(row=3, column=0, sticky=tk.E)
label5.grid(row=4, column=0, sticky=tk.E)
label6.grid(row=5, column=0, sticky=tk.E)
label7.grid(row=6, column=0, sticky=tk.E)
label8.grid(row=7, column=0, sticky=tk.E)
entry1.grid(row=0, column=1, sticky=tk.E)
entry2.grid(row=1, column=1, sticky=tk.E)
entry3.grid(row=2, column=1, sticky=tk.E)
entry4.grid(row=3, column=1, sticky=tk.E)
entry5.grid(row=4, column=1, sticky=tk.E)
entry6.grid(row=5, column=1, sticky=tk.E)
entry7.grid(row=6, column=1, sticky=tk.E)
entry8.grid(row=7, column=1, sticky=tk.E)
button1.grid(row=8, column=2, sticky=tk.E, padx=5, pady=5)
button2.grid(row=8, column=1, sticky=tk.E, padx=5, pady=5)

window.mainloop()